name: tp_router_generator
description: Code generator for tp_router annotations.
version: 0.0.1
homepage: https://github.com/user/tp_router

environment:
  sdk: '>=3.9.0 <=3.9.9'

dependencies:
  build: 
  source_gen: 
  analyzer: ^8.1.1
  glob: ^2.1.0
  tp_router_annotation:
    path: ../tp_router_annotation

dev_dependencies:
  build_test: 
  test: ^1.24.0
